### ISSUE TITLE
solids4foam-v2.0 release criteria

### ISSUE THREAD

**Issue by solids4foam** [solids4foam/solids4foam#1]
Following on from the suggestions at https://bitbucket.org/philip_cardiff/solids4foam-release/issues/50/next-release, this issue lists criteria that need to be met (or it would be nice to have) before the official release of soldis4foam-v2.0.
In addition, general open questions and considerations are listed.

# General
- Which OpenFOAM versions should be supported?
- The `filesToReplace` approach needs to be removed. It is too intrusive to ask users to change their installations.
- Is Eigen really needed? If it is, then let's make it an option using a compiler flag, e.g. S4F_USE_EIGEN
- Website (minimal website required), mail list, discussion forum (discourse), LinkedIn?, logo
- Defining the goal and scope of s4f
    - we do not want to re-implement everything from OF
        - minimise code duplication
        - implement just a few general fluid models
    - code maintenance should be a priority
    - what is the purpose of tutorials?
        - "quick" demonstration of feature?
        - what about benchmarking? maybe benchmarks should be in a separate repo
            - also, benchmark fe vs of.org vs of.esi
        - all tutorials should run on all versions: look for "solids4Foam::caseOnlyRunsWithFoamExtend"
    - applications? bio, wind, wave, etc., example cases?

# Website
-  [x] How to get started / Quickstart: installations instructions
    - [x] from source
    - [x] via Docker; what about binaries for Ubuntu
    - [x] tutorials: migrate from current documentation
    - [x] example using preCICE
    - example comparing different solid models: leave for future website updates
    - benchmarks: leave for future website updates
    - code and feature documentation: in progress
    - YouTube installation tutorial: leave for future website updates
    - [x] Update installation guide on the website: add Quickstart section

# Build
- [x] build passes on all supported versions of OpenFOAM
- [x] build script should tell the user if it failed
- [x] clearly define dependencies in the README and website and give instructions
    - PETSc
    - gfortran
    - Eigen
    - cfMesh: only needed for running a few tutorials, not needed for building
    - gnuplot: only needed for generating plots in a few tutorials, not needed for building

# Testing
- [x] Ideally, automated build system: adapt existing Jenkins system or use Github actions/pipelines
- [x] Tutorials pass Alltest on all supported versions
- [x] Tutorials complete Allrun on all supported versions
- Ideally, we would also perform some benchmarks between versions to check the answers are correct

# Code and modelling features
- Not done: Add benchmark data repo as a sub-module; this repo is quite large so it is better to leave this as optional; also it causes problem with the docker push action.
- [x] Update headers in all case files
- [x] Update headers in all source files: remove OpenFOAM symbol
- [x] Tag latest v1* and tag nextRelease v2*
- [x] Create zips for tagged versions and add to website
- [x] Agree on style and conventions
    - tags, e.g. v2.0.0
    - git: branch names, commit messages, pull request rules

**Comment by philipcardiff** [comment]
Most points have been covered; any outstanding points will be left for future updates.
