### ISSUE TITLE
easy and clean block coupling for s4f?

### ISSUE THREAD

**Issue by denMaier** [solids4foam/solids4foam#107]
Hey all,

i just found fppimenta/rheoTool and thought I'm leaving this here in case it could be useful someday.

In the library, you can find some interfaces to PETSc, Eigen and Hypre. 
With these interfaces it gets pretty easy and clean to add block coupling to any solver.

One just has to initialize a coupled solver with

```
//- Create coupled solver
autoPtr<coupledSolver>  cps
(
  new coupledSolver("DSigma",mesh.name(),runTime,mesh.solutionDict())
);

//- Add fields to coupled solver
 cps->insertMesh(mesh);
 cps->insertField(sigma);
 cps->insertField(D);  
```
This initiates a empty block coupled matrix for the stress-displacement coupling:
```math
\left \lbrack \matrix{DEqn & sigmaDEqn \cr DsigmaEqn & sigmaEqn } \right \rbrack \left \lbrack\matrix{D \cr s}\right \rbrack =   \left \lbrack\matrix{RHS_D \cr RHS_{sigma}}\right \rbrack
```
To fill the diagonal sub-matrices, one can just build the usual fvMatrixes:
```
fvVectorMatrix DEqn(
fvm::d2dt2(D) == .... )

fvSymmTensorMatrix sigmaEqn(
  diagonal ones // or fvm::ddt(sigma) for incremental form
)
```
and use 
```
cps->insertEquation
(
 D.name(), 
 D.name(),
 DEqn
);
cps->insertEquation
(
 sigma.name(), 
 sigma.name(),
 sigmaEqn
);
```
For the off-diagonal (coupling) sub-matrices, the new namespace fvmb:: has to be used:
```
cps->insertEquation
(
 D.name(),
 sigma.name(),
 fvmb::div(1., sigma)
);
cps->insertEquation
(
 sigma.name(),
 D.name(),
 fvmb::twoSymmGrad(mu,D) + fvmb::div(lambda,D)*symmTensor::I
);
```
and solve:
```
// Solve all coupled
              cps->solve(); 
```

More Fields can be block coupled as well, just:  `cps->insertField(---);` 
This can be done at a later state after the initial initialization of the matrix, which makes it very flexible.

What do you think? Cons are the need to compile PETSc etc. and maybe it's not flexible enough for your needs?

**Comment by philipcardiff** [comment]
Thanks @denMaier, very interesting. I agree that a clean and easy-to-use/maintain/extend/understand coupled matrix interface will become increasingly important.

Currently, PETSc is used in solids4foam in the [`vertexCentredLinGeomSolid`](https://github.com/solids4foam/solids4foam/blob/development/src/solids4FoamModels/solidModels/vertexCentredLinGeomSolid/vertexCentredLinGeomSolid.C) solid model; see the `evolve` function where I created a simple general [sparseMatrix](https://github.com/solids4foam/solids4foam/blob/development/src/solids4FoamModels/numerics/sparseMatrix/sparseMatrix.H) class, e.g.
```
        sparseMatrix mat;
        mat(1, 0) = tensor(1,2,3,4,5,6,7,8,9);
        mat(0, 2) += 3*I;
```
@federico081997 is working on extending this vertex-centred solver in his [fork](https://github.com/federico081997/solids4foam); currently, we want to add the pressure equation (displacement + pressure), so generalising the matrix interface is timely.

The RheoTool approach is nice; I can see they created new discretisation implementations (e.g. `fvmb::`) just like we are (`vfvm::`), which becomes a challenge when aiming for generality (e.g., in our case, vertex-centred stencils are different from cell-centred stencils).

I agree that it would be better if this could be done internally without the need for PETSc, but currently, PETSc offers many features that are not available within OpenFOAM. Mostly I have not had an issue installing or building PETSc so it may be an OK compromise. As a backup, the coupled interface could be independent of the linear solver and PETSc could be just one option, if it was installed. I created an ugly version of this in  `vertexCentredLinGeomSolid` where Eigen or PETSc can be used.

**Comment by denMaier** [comment]
> Thanks @denMaier, very interesting. I agree that a clean and easy-to-use/maintain/extend/understand coupled matrix interface will become increasingly important.
> 
> Currently, PETSc is used in solids4foam in the [`vertexCentredLinGeomSolid`](https://github.com/solids4foam/solids4foam/blob/development/src/solids4FoamModels/solidModels/vertexCentredLinGeomSolid/vertexCentredLinGeomSolid.C) solid model; see the `evolve` function where I created a simple general [sparseMatrix](https://github.com/solids4foam/solids4foam/blob/development/src/solids4FoamModels/numerics/sparseMatrix/sparseMatrix.H) class, e.g.
> 
> ```
>         sparseMatrix mat;
>         mat(1, 0) = tensor(1,2,3,4,5,6,7,8,9);
>         mat(0, 2) += 3*I;
> ```
> 
> @federico081997 is working on extending this vertex-centred solver in his [fork](https://github.com/federico081997/solids4foam); currently, we want to add the pressure equation (displacement + pressure), so generalising the matrix interface is timely.
> 
> The RheoTool approach is nice; I can see they created new discretisation implementations (e.g. `fvmb::`) just like we are (`vfvm::`), which becomes a challenge when aiming for generality (e.g., in our case, vertex-centred stencils are different from cell-centred stencils).
> 
> I agree that it would be better if this could be done internally without the need for PETSc, but currently, PETSc offers many features that are not available within OpenFOAM. Mostly I have not had an issue installing or building PETSc so it may be an OK compromise. As a backup, the coupled interface could be independent of the linear solver and PETSc could be just one option, if it was installed. I created an ugly version of this in `vertexCentredLinGeomSolid` where Eigen or PETSc can be used.
