### ISSUE TITLE
Error with StVenantKirchhoffOrthotropicElastic

### ISSUE THREAD

**Issue by andyvaldes10** [solids4foam/solids4foam#131]
I'm trying to model a structure with `StVenantKirchhoffOrthotropicElastic` (NonLinear Geometry Laws) and for that I was thinking of using OpenFOAM 9, but when I run `./Allwmake`, this is the only model that doesn't come out. Checking the `files.openfoam` file it doesn't show up. I tried to add a line manually as written in` file.foamextend` : `$(nonLinGeomLaws)/StVenantKirchhoffOrthotropicElastic/StVenantKirchhoffOrthotropicElastic.C` and install it from scratch, but it gives me an error. _In foam-extend this model works_.

_Is not compatible with OpenFOAM 9?_

A part of the error: 
`materialModels/mechanicalModel/mechanicalLaws/nonLinearGeometryLaws/StVenantKirchhoffOrthotropicElastic/StVenantKirchhoffOrthotropicElastic.H:120:17: error: ‘volSymmTensor4thOrderField’ does not name a type; did you mean ‘SymmTensor4thOrder’?
         mutable volSymmTensor4thOrderField* elasticCPtr_;
`
`        
 ^~~~~~~~~~~~~~~~~~~~~~~~~~
                 SymmTensor4thOrder
materialModels/mechanicalModel/mechanicalLaws/nonLinearGeometryLaws/StVenantKirchhoffOrthotropicElastic/StVenantKirchhoffOrthotropicElastic.H:124:17: error: ‘surfaceSymmTensor4thOrderField’ does not name a type; did you mean ‘surfaceSymmTensorField’?
         mutable surfaceSymmTensor4thOrderField* elasticCfPtr_;
`

**Comment by philipcardiff** [comment]
Correct. Unfortunately, `volSymmTensor4thOrderField` and related classes are only available in foam extend. A workaround would be to use some other container to store the 4th order tensors (e.g. Matrix class in OpenFOAM.com), but this would take a bit of coding.
