### ISSUE TITLE
Undocumented OpenFOAM version compatibility for tutorial cases

### ISSUE THREAD

**Issue by MakisH** [solids4foam/solids4foam#149]
Trying to run the [beamInCrossFlow](https://www.solids4foam.com/tutorials/tutorial3.html) tutorial with OpenFOAM v2312, I got the following output:

```
tutorials/fluidSolidInteraction/beamInCrossFlow [(v2.1)]$ ./Allrun 
No OpenFOAM tutorials? : /usr/lib/openfoam/openfoam2312/tutorials
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
| solids4Foam::convertCaseFormat start                                |
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Changing symmetryPlane to symmetry in blockMeshDict

Replacing system/functions with system/functions.openfoam
Changing RASModel to RAS in turbulenceProperties
Changing timeVaryingUniformFixedValue to uniformValue in p
OpenFOAM.com specific: replacing 'leastSquares' with 'pointCellsLeastSquares' in system/solid/fvSchemes
Modifying force.gnuplot in consistent with ESI version

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
| solids4Foam::convertCaseFormat end                                  |
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


This case currently does not run with this OpenFOAM verion
```

Searching for the error message, I understand that this appears in:

- [ ] `fluidSolidInteraction/beamInCrossFlow/Allrun`
- [ ] `fluidSolidInteraction/flexibleDamBreak/Allrun`

For both, the check seems to be `if (( "${WM_PROJECT_VERSION#v}" > 2012 ))`. This seems to not be documented in the `README.md` of the respective tutorials, and the error message does not give any hints on which versions would be valid.

In the documentation, where this is explained, I would also expect some details on what exactly is incompatible.

This is in the context of my review for the JOSS publication (https://github.com/openjournals/joss-reviews/issues/7407).

**Comment by iBatistic** [comment]
The check in beamInCrossFlow and flexibleDamBreak was removed in commit c66a480. It had already been removed in the feature branch we worked on recently, but we did not remove it from the development branch. I believe there was an issue with version v2312, but Philip resolved it. The valid versions are listed in the Allwmake script.
@philipcardiff, could you please confirm if I’m right? If so, we can close the issue.

**Comment by philipcardiff** [comment]
Yep, this seems to be resolved.

**Comment by philipcardiff** [comment]
Closing as resolved. As discussed above, commit c66a480 removed the obsolete version checks; that change has now reached `master`/v2.3.
