### ISSUE TITLE
sonicLiquidFluid should be updated to be the same as the standard OF9, OFv2012 and FE41 versions 

### ISSUE THREAD

**Issue by philipcardiff** [solids4foam/solids4foam#15]
Currently, there is only one version of sonicLiquidFluid, which works with the three OpenFOAM forks.

For consistency with the standard sonicLiquidFoam solvers, we should port sonicLiquidFoam from OF9, OFv2012 and FE41, for example, as is done for pimpleFluid. In that case, we would have sonicLiquidFluid.esi.C, sonicLiquidFluid.foundation.C, etc.

**Comment by iagolessa** [comment]
Hey @philipcardiff, 
FYI, in my pull request of the Robin conditions, I performed that "splitting" of sonicLiquidFluid as you can see in commit [087809d](https://github.com/solids4foam/solids4foam/pull/14/commits/087809dcd4ff9471f0972758e2b8fa85cb20ca3e). Regarding the version for OF9, I left the code even though I noticed that OF9 does not have a sonicLiquidFoam solver anymore (they have dropped it after OF6, as far as I could assess). But the code still works with OF9.

**Comment by philipcardiff** [comment]
Thanks @iagolessa,

OK, from the [release notes for OF7](https://openfoam.org/release/7/), it says:
> Solvers:  The sonicFoam, sonicDyMFoam and sonicLiquidFoam are deprecated since their functionality has been merged into the rhoPimpleFoam solver, running the transonic option [[ commit 3341f9 ]](https://github.com/OpenFOAM/OpenFOAM-dev/commit/3341f925108a759f58f06ce2fd865321af6dd6ca).  Added LTS capability to pimpleFoam, providing the option to accelerate solutions to steady-state [[ commit e1e3e2 ]](https://github.com/OpenFOAM/OpenFOAM-dev/commit/e1e3e2a33303b85c002edc15b484e00a2ea34ec5)

So, what should we do... 

If the ESI version of sonicLiquidFluid compiles with OF9, we can leave it.
Alternatively, we just remove sonicLiquidFluid for the foundation version, but then we should port rhoPimpleFoam (for at least OF9).

**Comment by philipcardiff** [comment]
I have now added it to the website repository ([https://github.com/solids4foam/solids4foam.github.io](https://github.com/solids4foam/solids4foam.github.io)).

You can see it deployed at [https://solids4foam.github.io/tutorials/tutorial4.html](https://solids4foam.github.io/tutorials/tutorial4.html).

One question: why does the Robin approach give the wrong answer for a smaller time-step? You would think that it would get better with a smaller time-step? Is it possible that the legend is wrong and the dt1e-4 and dt2.5e-5 results are mixed up?

**Comment by iagolessa** [comment]
> If the ESI version of sonicLiquidFluid compiles with OF9, we can leave it. Alternatively, we just remove sonicLiquidFluid for the foundation version, but then we should port rhoPimpleFoam (for at least OF9).

I agree that we can leave it available for the moment, especially because sonicLiquidFluid proved a good alternative to stabilize and improve the convergence of some FSI cases. I wonder whether a more elaborate compressible model would cause the same behaviour for FSI. I can make some tests with a ported version to assess whether it could be a good alternative and then replace sonicLiquidFluid.

**Comment by iagolessa** [comment]
> One question: why does the Robin approach give the wrong answer for a smaller time-step? You would think that it would get better with a smaller time-step? Is it possible that the legend is wrong and the dt1e-4 and dt2.5e-5 results are mixed up?
Nice :)
Regarding the Robin solution: according to the original paper, that solution was the expected one with a smaller time-step. I am not quite sure what explains that, but, as far as I know, FSI partitioned algorithms, in general, are pretty sensible to time-step values and temporal discretization. For example, it is reported that the onset of instabilities in partitioned FSI calculation occurs earlier when decreasing the time-step. So, this could explain the deterioration of the solution (I think I should have added that in the README.md).  
What was a surprise for me was the deterioration of the coupling performance too, which approaches the purely incompressible behavior. For that, so far, I could not find an explanation.

**Comment by philipcardiff** [comment]
My understanding is that weakly coupled algorithms suffer from instabilities as the time step is reduced; however, strongly coupled algorithms do not.

In [https://www.sciencedirect.com/science/article/abs/pii/S0045782506002544?via%3Dihub](https://www.sciencedirect.com/science/article/abs/pii/S0045782506002544?via%3Dihub), they discuss weak (also called staggered or loose by them) and strong schemes and only comment on the small time-step instability for weakly coupled schemes:

> It has been observed that so-called loose coupling of fluid and structural part in the context of incompressible flow and slender structures frequently yields unstable computations. Surprisingly the instability depends upon the densities of fluid and structure and also on the geometry of the domain [1], [2], [3], [4]. Clearly sequential coupling introduces an explicit flavour into the computation even if both partitions themselves are solved implicitly. Thus restrictions on the time step have to be expected. Observations however show that decreasing of the time step results in an increased instability. The instability is inherent in the scheme itself and has been named ‘artificial added mass effect’ since major parts of the fluid act as an extra mass on the structural degrees of freedom at the coupling interface. In sequentially staggered schemes the fluid forces depend upon predicted structural interface displacements rather than the correct ones and thus contain a portion of incorrect coupling forces. It is this ‘artificial’ contribution to the coupling which yields the instability.


In [https://hrcak.srce.hr/206941][https://hrcak.srce.hr/206941], time-step independent results are achieved for the "beam in a crossflow" case.
Also, in [https://link.springer.com/chapter/10.1007/978-3-319-60846-4_1](https://link.springer.com/chapter/10.1007/978-3-319-60846-4_1), where this BC was introduced, they show time-step independent results for this case (Fig. 8), where they actually use a loose scheme in that case.
I guess it makes sense to benchmark against the time-step independent solution (or close to it).

We could check if the other approaches converge as the time-step is reduced.

**Comment by philipcardiff** [comment]
By the way, @iagolessa, how to you extract the number of iterations for plots?

**Comment by philipcardiff** [comment]
Another thought I had is that it would be useful to store these results (e.g. the postProcessing directory and maybe the log file) for each comparative run in the 3dTube case; that way, we can compare other techniques we might try in the future.

It's probably not a good idea to pollute the main repository with these results, but maybe a parallel repository could be dedicated to storing reference results. It could follow the same tutorial tree structure. Let me know your thoughts.

**Comment by philipcardiff** [comment]
I tried a time-step study using sonicLiquidFluid, Aitken's and the Euler time scheme and the expected 1st order convergence was observed.
![3dTube_radialDispPointA_Aitkens_sonicLiquidFoam_Euler_OpenFOAMv2012](https://user-images.githubusercontent.com/25078503/205881943-e195b564-6859-445d-87d0-58e7e9fc32ec.png)

I have created a new repository ([here](https://github.com/solids4foam/solids4foam-tutorials-benchmark-data)) to store this data. Feel free to create a pull request to push your data.

I will now try a few different settings to see how the convergence is affected, in particular to check if the Robin approach converges in time.

**Comment by iagolessa** [comment]
> By the way, @iagolessa, how to you extract the number of iterations for plots?

I used a simple bash concatenated command to get the number of iter. per time-step, given the log file of a case:
`cat <log-file-path> | grep '^Time = .*' | grep -B1 '^Time = [0-9]\.[0-9]*$' | grep '^Time = .*,.*' |  cut -d' ' -f 3,5 |  tr -d ','`

> Another thought I had is that it would be useful to store these results (e.g. the postProcessing directory and maybe the log file) for each comparative run in the 3dTube case; that way, we can compare other techniques we might try in the future.
> 
> It's probably not a good idea to pollute the main repository with these results, but maybe a parallel repository could be dedicated to storing reference results. It could follow the same tutorial tree structure. Let me know your thoughts.

Sure, I will add my trials and take the opportunity to also add the scripts I used to post-process and plot them in gnuplot. They might be useful.
 
> I will now try a few different settings to see how the convergence is affected, in particular to check if the Robin approach converges in time.

About the solution convergence and temporal behavior, the results I got and posted in the online tutorial reproduced the behavior of the original paper that you mentioned and are similar to your plot in the above answer (although I only added two time-steps, 2.5e-5s and 1e-4s). What surprised me was exactly the effect on the convergence when changing the time-step with the Robin BCs, which deteriorates a lot. This was not explored in the original publication of this BC, and I didn't find any suggestion that this would be normal behavior of these Robin BCs.

**Comment by iagolessa** [comment]
> Interestingly (and consistent with your comments on small time-step instability), using the 2nd order backward time scheme (both solid and fluid) leads to instabilities for smaller time-steps: ![3dTube_radialDispPointA_Aitkens_sonicLiquidFoam_backward_OpenFOAMv2012](https://user-images.githubusercontent.com/25078503/205925136-7a3d423e-291f-4c9b-8779-b264fd1087ce.png)

Nice! These are very instructive actually for people looking at FSI problems! 
Did you already compared the FSI iterations wiht these results? It might also be interesting to see if the solution convergence deteriorates too with the time-step when using the "traditional" BC of the Dirichlet-Neuman formulation, as occurred with the Robin BC that I posted in the website.

>I will see if it makes a difference if IQNILS is used instead of Aitkens...

It could be in this simpler benchmark. My experience when using it in the more complex arterial geometries is that it helps with the convergence speed, but at some point the instability still ccurs...

**Comment by philipcardiff** [comment]
Here is the comparison (I will add these results to the benchmark repo):
![3dTube_radialDispPointA_Aitkens_sonicLiquidFoam_EulerVsBackward_OpenFOAMv2012](https://user-images.githubusercontent.com/25078503/205928207-f3d232e3-541f-49ac-ba4f-5d4c397ce523.png)

It is clear that backward is more accurate than Euler, but instabilities occur for smaller time steps.

I have not checked the number of iterations. How do you extract them? Do you do it from the log, the fsiResiduals.dat file, or something else?

**Comment by philipcardiff** [comment]
By the way, I agree these studies would be useful to present on the website.

**Comment by philipcardiff** [comment]
Also, I think these results also clarify my original question about why the `RNF-dt2.5e-5` results were different: the answer is that the deltaT=1e-4 results still contain significant temporal errors.

Maybe a good idea for the 3dTube README.md would be to have two figures:
- one which compares the results for four coupling approaches for the same time-step (e.g., 1e-4);
- one which compares the results for different time steps using one (or more) coupling algorithm(s).

**Comment by philipcardiff** [comment]
> cat <log-file-path> | grep '^Time = .*' | grep -B1 '^Time = [0-9]\.[0-9]*$' | grep '^Time = .*,.*' | cut -d' ' -f 3,5 | tr -d ','

For some reason, I had to remove `^` from before `Time` (second and third instance but not the first) in the command to get it to work (I am using GNU grep on macOS, which should be the same, but maybe there is some other difference related to piping). The command that works for me is:

     cat ./sonicLiquidFoam/aitkens/backward/deltaT1e-4/log.solids4Foam | grep '^Time = .*' | grep -B1 'Time = [0-9]\.[0-9]*$' | grep 'Time = .*,.*' | cut -d' ' -f 3,5 | tr -d ','

**Comment by philipcardiff** [comment]
Also, FYI, IQNILS shows the same instabilities as Aitken when using backward and smaller time steps.

**Comment by philipcardiff** [comment]
FYI, using the Robin approach with the backward scheme crashes; in elasticWallVelocity I can see that both Euler and backward methods are allowed, but maybe the backward approach was not well tested.

**Comment by philipcardiff** [comment]
The Robin approach seems to need a smaller time-step than the other approaches to be stable: 1e-4 is the largest stable time-step for Euler. However, for smaller time steps than this, it is very fast and only requires a small number of iterations. In the paper, the largest time step they use is 5e-5 s, which is the smallest I have used here.

Once the runs finish, I will post the results here. I suspect that backward actually does work, assuming a small enough time-step is used. For Euler, I notice that the Aitken relaxation factor is 1.0 so the cases could probably be accelerated by using a larger starting relaxation factor too.

**Comment by philipcardiff** [comment]
Some interesting results for the Robin+Aitkens+pimple approach:
![3dTube_radialDispPointA_Aitkens_Robin_pimpleFoam_Euler_foam-extend-4 1](https://user-images.githubusercontent.com/25078503/206015201-54be038e-9e29-4f4d-bb27-b729f70ac092.png)
![3dTube_numberOfInterations_Aitkens_Robin_pimpleFoam_Euler_foam-extend-4 1](https://user-images.githubusercontent.com/25078503/206015231-ca3dc7a2-6b87-471a-9fd9-dd3d4325c21e.png)

In short:
- This method works well for "small" time steps, requiring around 4 iterations.
- It fails for larger time steps, whereas the Dirichlet-Neumann and weakly compressible approaches do not fail. You can see that the largest time step (1e-4) requires many iterations; for larger time steps, it crashes.
- Looking at the convergence, ideally, we would like a second-order time scheme in this case. I will not check if the backward scheme will work with these time steps.

**Comment by philipcardiff** [comment]
Tutorial 4 has now been updated at [https://solids4foam.github.io/tutorials/tutorial4.html](https://solids4foam.github.io/tutorials/tutorial4.html).
