### ISSUE TITLE
Robin conditions with OpenFOAM-9 and OpenFOAM-v2012

### ISSUE THREAD

**Issue by philipcardiff** [solids4foam/solids4foam#26]
Currently, the Robin conditions are only correctly implemented for foam-extend-4.1.

It would be useful to implement them also for OpenFOAM-9 and OpenFOAM-v2012; the boundary conditions themselves compile correctly, but changes are required in pimpleFluid for the respective versions.

**Comment by philipcardiff** [comment]
For OpenFOAM-v9, see the recent commits to the `development` branch:
- ca2055177b9360fc0a10e16340c9b2172e5bb112
- 79f88b1e664f1b1fee7d421d31112f197c39c5ac
- c9c8e8380488bbfefeaf634171b2a1a3559f522c
- 336a8bc2c917d93596e8a5e747f88cabfa2a91f7
- b3716a6ab1b186081e2959a672a9c84bbc4388d1

The next step is to benchmark the performance on the [3dTube](https://solids4foam.github.io/tutorials/tutorial4.html) case.

@iagolessa , have a quick look and let me know if you think anything is missing. Currently, `3dTube` is diverging at Time = 0.00095 s, when I use deltaT = 2.5e-5 s and the 1st order Euler scheme; whereas foam-extend-4.1 requires 5 FSI iterations per time step as described at  [https://solids4foam.github.io/tutorials/tutorial4.html](https://solids4foam.github.io/tutorials/tutorial4.html).

Thanks @SimoMor87; feel free to comment if you see that I made a mistake.

**Comment by philipcardiff** [comment]
FYI, the port was used here: [https://zenodo.org/record/7995669](https://zenodo.org/record/7995669)

**Comment by SimoMor87** [comment]
I don’t see any mistakes.  I completed the 3dTube simulation by replacing the elasticWallPressure BC with robin BC. ElasticWallPressure BC has always given me problems making diverging simulations.

**Comment by philipcardiff** [comment]
Thanks, Simona, can you attach your `0` directory here?

**Comment by SimoMor87** [comment]
Yes!

[0.zip](https://github.com/solids4foam/solids4foam/files/11849133/0.zip)

**Comment by philipcardiff** [comment]
Is it possible to also attach your (wclean-ed) solids4FoamModels directory?
I am not getting the same before as in your log file; I may be missing some other important change.

I see that you are setting the Robin coefficients manually; I guess the elasticWallPressure condition is meant to set these automatically, but I guess your manual values must be better in this case.

**Comment by philipcardiff** [comment]
I spoke too soon; the 3dTube case now seems to be working with the elasticWallPressure case for me. Let me double-check a few things and see if I made any other important changes.

**Comment by philipcardiff** [comment]
FYI, @ztukovic, this may be of interest.

**Comment by philipcardiff** [comment]
Resolved in https://github.com/solids4foam/solids4foam/pull/59
