### ISSUE TITLE
solidModelsTemplate.C   solver IO information 

### ISSUE THREAD

**Issue by XuliaDS** [solids4foam/solids4foam#33]
Hi!
I was looking at the convergergence history for every correction and noticed (or so I think) that the solver can give a false converged status info ( screen ).
 
In file solidModelsTemplate.C 

The else if in line 133
else if (iCorr % infoFrequency_ == 0 || converged)

will enter if iCorr % infoFrequency_ == 0 (regardless converged is true or not) so the next else if (line 155 )

else if (iCorr == nCorr_ - 1 && !converged)

will never be reached if iCorr % infoFrequency_ == 0 (regardless the variable converged is true or not and we are at the last iteration because it already entered the previous else if). As a result, you don't increment the maxIterReached_++
and in the final call in solidModel.C (line 1737, function ::end() ) prints that everything has converged. 
Which is not true. Does this make sense ??

Maybe I am missing something 

Cheers,
Xulia

**Comment by philipcardiff** [comment]
Hi Xulia,

Thanks for this. Yes, I can now see that there is an error here. Normally, I set `infoFrequency_` to a large-ish number, so I was less likely to see this issue. But if `infoFrequency_ == 1`, the `Max iterations reached within momentum loop` warning will never be printed.

A simple fix could be to replace this line
```
else if (iCorr == nCorr_ - 1)
```
with
```
if (iCorr == nCorr_ - 1)
```

Possibly, `&& !converged` could be added too.

**Comment by XuliaDS** [comment]
Hello !
yes, that's the fix I did in my computer

if (iCorr == nCorr_ - 1 && !converged)
{
maxIterReached_++;
Warning
<< "Max iterations reached within momentum loop" << endl;
}

Cheers and thanks for making this software public :)

**Comment by philipcardiff** [comment]
Resolved in 33aa686f on the `development` branch.
