### ISSUE TITLE
Consider using system Eigen by default

### ISSUE THREAD

**Issue by fsimonis** [solids4foam/solids4foam#4]
Currently, solids4foam downloads the desired Eigen version unless the env `EIGEN_DIR` points to an existing installation.

This practise is error-prone as it may easily violate the one definition rule (ODR).
If not otherwise specified, the generally expected behaviour of a build system is to use the version of a library installed on the system by default.
So, all it takes to violate ODR is a single other library in the application to use a different version of Eigen.

I suggest to keep `EIGEN_DIR` as an override and use the system-provided Eigen version as the default.
A commonly used tool to detect this is `pkg-config`.

```console
$ pkg-config -cflags eigen3
-I/usr/include/eigen3
```

You can use `pgk-config --exists eigen3` to verify if eigen3 is installed.

This works on the vast majority of distributions and platforms, as well as package managers such as Spack.

See also https://github.com/precice/tutorials/pull/286

**Comment by philipcardiff** [comment]
Hi fsimonis,

Thanks for the suggestion.

I have now modified the installation behaviour to look for a system installation of Eigen first before resorting to a local installation. See commits 90a806d5e693e40bda24c557977ab15632b07a2c and the related commits 869ef48264cece64fb20bfcdc89d62c2dccecd88 and 6ed5dbda3453207ba8f36051044b19165ceeabf1.

Also, in the commits above, I have added the option for solids4foam not to use Eigen if the `S4F_NO_USE_EIGEN` variable is set, i.e. solids4foam is installed without Eigen with:
```
export S4F_NO_USE_EIGEN=1 && ./Allwmake
```

By the way, the `pgk-config --exists eigen3` command works for (most?) Linux but, alas, not for macOS (which I use by default). I found a relatively general solution by searching for the `signature_of_eigen3_matrix_library` file, e.g. see [https://github.com/solids4foam/solids4foam/blob/nextRelease/ThirdParty/Allwmake](https://github.com/solids4foam/solids4foam/blob/nextRelease/ThirdParty/Allwmake); actually, it seems that the entire purpose of `signature_of_eigen3_matrix_library` is to help people find the Eigen installation.

**Comment by fsimonis** [comment]
Thanks for looking into it!

> By the way, the pgk-config --exists eigen3 command works for (most?) Linux but, alas, not for macOS (which I use by default).

The behaviour depends on the used implementation (pkg-config or pkgconfig) and how your system is setup. It could be that you have to manually add search paths.

> I found a relatively general solution by searching for the signature_of_eigen3_matrix_library file, e.g. see https://github.com/solids4foam/solids4foam/blob/nextRelease/ThirdParty/Allwmake; actually, it seems that the entire purpose of signature_of_eigen3_matrix_library is to help people find the Eigen installation.

True, the FindEigen3 CMake module also searches for the signature file.

**Comment by philipcardiff** [comment]
Resolved in:
- https://github.com/solids4foam/solids4foam/commit/90a806d5e693e40bda24c557977ab15632b07a2c
- https://github.com/solids4foam/solids4foam/commit/869ef48264cece64fb20bfcdc89d62c2dccecd88
- https://github.com/solids4foam/solids4foam/commit/6ed5dbda3453207ba8f36051044b19165ceeabf1.
