### ISSUE TITLE
Successful v2112 compilation

### ISSUE THREAD

**Issue by burgreen** [solids4foam/solids4foam#45]
The new github and git.io sites are great. 

I have successfully compiled solids4Foam against v2112 (and ran one test case successfully).

One simply needs to replace every occurrence of `*Table::iterator` with `auto` (yes, sloppy auto hack). For example,
```
    //fix IstreamConstructorTable::iterator cstrIter =
    auto cstrIter =
        IstreamConstructorTablePtr_->find(schemeName);
```
Compiles in v2112 with no errors. 

Regards,
Greg Burgreen

**Comment by denMaier** [comment]
that's great news!

**Comment by philipcardiff** [comment]
Thanks, Greg!

Mark Olesen included this general fix (and a simplification of the build options) in https://github.com/solids4foam/solids4foam/pull/60, which has now been merged into the development branch.

Nonetheless, I have added your name to the CONTRIBUTORS.md in eed35081 to mark this helpful contribution (this will appear at https://www.solids4foam.com/about/CONTRIBUTORS.html).

**Comment by philipcardiff** [comment]
Resolved in https://github.com/solids4foam/solids4foam/pull/60
