### ISSUE TITLE
DD fields are not being written for solids4Foam v2

### ISSUE THREAD

**Issue by suyashverma9** [solids4foam/solids4foam#67]
Hi Phillip

I noticed for various tutorial cases, that 'DD' field is not written for any timestep. So running the case from a checkpoint results in error:

--> FOAM FATAL ERROR: (openfoam-2012)
This solidModel requires the 'DD' field to be specified!

    From nonLinearGeometryUpdatedLagrangian::DDisRequired()
    in file solidModels/solidModel/solidModel.C at line 1522.

FOAM aborting

Am I missing something here?. I have had experience with solids4Foam v1, and the solver does write DD fields on output.

**Comment by philipcardiff** [comment]
Thanks @suyashverma9, can you give an example of an existing tutorial that shows this issue? And what commands/changes I need to show this issue?

**Comment by philipcardiff** [comment]
Try adding the `restart` flag inside the solid model dictionary in `solidProperties` (e.g. in `constant/solid/solidsProperties` in `3dTube`), e.g.
```
"linearGeometryCoeffs|linearGeometryTotalDisplacementCoeffs|nonLinearGeometryUpdatedLagrangianCoeffs"
{
    // other settings
    // ...

    // Write all fields needed for a consistent restart (defaults to "no")
    restart yes;

    // other settings
    // ...
}
```

Sorry, this setting is currently poorly documented!

**Comment by philipcardiff** [comment]
I will close this issue now, although, if you like, feel free to make a new issue stating that this restart feature is not well described.
You will see that the documentation on the website is slowly getting better (feel free to contribute!).

**Comment by suyashverma9** [comment]
Yes, I definitely agree and would be glad to contribute in any way in future. Created the new issue as suggested.

Thanks for your prompt fix again.
