### ISSUE TITLE
Add GitHub action based on solids4FoamChangeCopyright.sh

### ISSUE THREAD

**Issue by philipcardiff** [solids4foam/solids4foam#69]
The solids4FoamChangeCopyright.sh script should be automatically called when there is a commit to ensure all code files have the correct header.

It would make sense to add this as a GitHub action, that returns an error if a file should be changed; this will then force developers to update the headers. Alternatively, the GitHub action could actually make these changes and commit them.

**Comment by iBatistic** [comment]
@philipcardiff should we close this, or we can leave it as a reminder to try automatic header changes?

**Comment by philipcardiff** [comment]
Yep, I think we can close it.

In 8e5f5bb6290777f7618151f09cb0feac96e976b2, I have manually updated all the src code file headers using the latest script.

And, the GitHub actions seems to correctly catch incorrect headers.

Automatic header changes may be overkill (and could be dangerous if we make a mistake) so we can put that aside.

Thanks!

**Comment by philipcardiff** [comment]
Resolved in https://github.com/solids4foam/solids4foam/pull/70
