### ISSUE TITLE
Write default values to the dict and write dict to disk

### ISSUE THREAD

**Issue by denMaier** [solids4foam/solids4foam#72]
There is an inherent problem with hardcoding default values via "lookupOrDefault<T>", that is the user should know what values have been used. If the user, for example uses other units or just doesn't know about some flags, he/she might never know that something is wrong.
For the sake of documentation and  traceability I would suggest using "lookupOrAddDefault<T>" instead, and writing all the IODicts to file in the end() functions of solidModel/FluidModel or fluidSolidInterface. 
This should work for v2XXX and .org versions, I dont know about FE.

**Comment by philipcardiff** [comment]
Thanks Denis,

Good point. FE41 has a `dict.lookupOrAddDefault` option so this fix should work for all versions.

Feel free to propose a pull request (or even a draft pull request), or someone (me?) will eventually do this!
