### ISSUE TITLE
cycle-by-cycle simulation

### ISSUE THREAD

**Issue by Youngxl1998** [solids4foam/solids4foam#74]
Hi Philip,
Is there a cyclic BC in solids4foam or fe 4.1 ,which can consider N sinusoidal velocity cycles for waves in fluid simulations? Do I need to implement a new BC myself or it is available directly? An alternative that I currently in mind is to do one-cycle in a time-series file with N copies, but it seems too uncomputerized.
Thanks!

**Comment by philipcardiff** [comment]
This does not seem to be a bug report or feature enhancement. For general queries like this, please use the www.cfd-online.com.

For periodic boundary condition, look at cyclicAMI or cyclicGGI.
