### ISSUE TITLE
incremental form of materialLaws

### ISSUE THREAD

**Issue by denMaier** [solids4foam/solids4foam#86]
at the moment the material laws are (all?) formulated in total form. 
However, i think the incremental form would be more flexible, since the total form can be translated into incremental form always. 

I'm trying to implement a hypo-elastoplastic material law, which by nature is incremental,
and it seems like I would have to rewrite functions like `updateEpsilon`.

Furthermore, from Simo & Hughes (2006) I found that we could use objective stress rates to use `linearGeom` material laws in `nonLinGeom` calculations (not pretty but practical).

What do you guys think?

**Comment by philipcardiff** [comment]
Hi Denis,

Thanks for the suggestions.

The current mechanical laws are neither total or incremental; it is the choice of the mechanical law. The only requirement is that they calculate the new (total) stress given the (total) strain, but they also have access to the old-time strain (e.g. epsilon.oldTime) so they can easily use the strain increment if they like, eg. `DEpsilon = epsilon - epsilon.oldTime();`. For example, `linearElasticMisesPlastic` uses the small-strain elasto-plastic algorithm from Simo and Hughes, which essentially needs DEpsilon.

Or maybe you are referring to so-called hypo-elastoplastic laws, using objective stresses. These could be implemented in the current approach, although I think these require the strains defined at the mid-time-step point (Hughes-Winget algorithm); in any case, it *should* be possible too. Or maybe you mean something else?

Allowing all `linGeom` laws to be called as `nonLinGeom` laws is a very useful idea. The objective stress rates (e.g. Jaumann) may be one way to achieve this, but I have experience using an alternative aprpoach based on a pre- and post-processing step, which allows the same thing. The algorithm is described in Caminero et al. (ref below) and I have an implementation from a previous project; I could revisit this and consider a general implementation.

More generally, I think a redesign of the material laws would be beneficial; for example, here are features I would like:
- Calculate stress for any size list, i.e. it could come from a volField, surfaceField, pointField, patch, other. This would avoid the need for correct(surfaceField) and correct(volField) and allow other cases without code repetition.
- Make mechanical laws in purely virtual functions/classes: do not store state data within a mechanical law; instead, the old and new state data should be passed into the calculate stress function. This reduces the code complexity and makes it easier to do things like calculate material tangents using numerical differentiation. State variables could be dealt with in a generic way using PtrList<volScalarField>.
- The general large strain formulation, like discussed above, allowing all material laws to work for nonlinear geometry.
- Follow material model interfaces closer to other software, like Abaqus and FLAC3D.

```
    Caminero, Montáns & Bathe, Modeling large strain anisotropic elasto-                                                                                           
    plasticity with logarithmic strain and stress measures, Computers and                                                                                          
    Structures, 2011, doi:10.1016/j.compstruc.2011.02.011. 
```

**Comment by denMaier** [comment]
Hey @philipcardiff , 

I have to admit, that I am still a bit confused about objectivity and algorithms that preserve it. So maybe I got something wrong.   As I understood for hypo-elastic and for hypo-plastic material laws, there are no closed form equations for stress, only incremental relations. When considering large deformations, the cauchy stress increment is not objective, so that corrections have to be added to the incremental laws or equivalently by bringing these corrections to the left-hand-side the stress and the corrections can be interpreted as an objective stress increment.
I was thinking, we could add a wrapper class that adds these corrections after the fact, similarly as we do it for pore-water pressure in poroMechanicalLaw now.
However, the algorithm by Caminero et al. sounds interesting, I will definitely have a look at that.

Additionally, I am tryping to implement the "Eularian projection method for quasi-static elastoplasticity" by Rycroft et al. since I'm building a Eularian solidModel for simulating penetration of structures into soil.
My idea was to implement the method in strict analogy to how the pimple-Algorithm is structured.
I thought i could just add the objectivity-corrections and the convective term for stress after the fact in a wrapper class.   

```
 Chris H. Rycroft, Yi Sui, Eran Bouchbinder,
An Eulerian projection method for quasi-static elastoplasticity,
Journal of Computational Physics,
Volume 300,
2015,
Pages 136-166,
https://doi.org/10.1016/j.jcp.2015.06.046. 
```

**Comment by denMaier** [comment]
I have been thinking about this topic quite a bit and here are my thoughts:

1. Calculate stress for any size list, i.e. it could come from a volField, surfaceField, pointField, patch, other. This would avoid the need for correct(surfaceField) and correct(volField) and allow other cases without code repetition.
> This is an excellent idea, I recently used the same approach to calculate relative (saturation dependent) hydraulic conductivity and it simplified the code enormously on multiple levels.
 
2.     Make mechanical laws in purely virtual functions/classes: do not store state data within a mechanical law; instead, the old and new state data should be passed into the calculate stress function. This reduces the code complexity and makes it easier to do things like calculate material tangents using numerical differentiation. State variables could be dealt with in a generic way using PtrList.
> About this I'm not 100%, I can definitely see the upsides, however, I could imagine, that different mechanicalLaws could need different state variables that most others don't use (e.g. in geomechanics the porosity is often a state variable) .
I think having a clear split between deformation measures and stress measures would be beneficial however: All fields related to the deformation should be held by the mechanical law (D,U,grad(D)/F etc.) and the stress fields held by mechanicalLaw. We could still give outside access to the stress by a function `sigma()` which returns `mechanicalLaw.sigma()`.
 
3. The general large strain formulation, like discussed above, allowing all material laws to work for nonlinear geometry.
    + Follow material model interfaces closer to other software, like Abaqus and FLAC3D.
>  Definitely worthwhile. I still believe, that returning the stress increment instead of stress is more versatile, since the solidModel can always add up to the current stress, if needed. In case the non incremental displacement is not available (as is the case in my mixture-Eularian approach, see below), one can solve the incremental form of the momentum balance (which is atm not done, even in the incremental solver or the updatedLagrangian solvers, where the total form is solved).

In addition to these thoughts, I am also trying to find a way to treat mixtures of materials because, as I mentioned before, I am trying to build an Eularian solver. Usually this is done by calculating the stresses for all materials in a cell and then adding them up according to their volumetric fraction in the cell. However, atm the materialLaws are attached to the cellZones. Maybe there is some way to make this attachment optional. I'm not sure yet, but it looks like this would have far reaching consequences for how materialLaws are treated, especially when multi-material boundaries are considered. So I might have to live with the fact that my solver can only solve with one material specified.

**Comment by philipcardiff** [comment]
Thanks for the comments, Denis.

For now, I suggest we keep this thread open and use it to discuss future re-designs of the material law classes. I think we should be able to find a solution that works well for most scenarios and is easily maintained, extended and understood.

We can possibly create this new structure in parallel with the existing structure, and temporarily maintain backward compatibility. 

Multi-material boundaries are definitely a pain and have significantly affected the current code design and understandability.

**Comment by denMaier** [comment]
hello all,

just leaving this here, so it's documented and whoever is interested can give it a thought.

I was just browsing through the code for the turbulanceModels in OpenFoam and I think we could learn a thing or two from them.

First of all they created a basicTurbulanceModel with the absolute minimum functionality. Now here's the new idea: They then made "sub"-basicTurbulanceModels for incomprehensible, compressible p-based and compressible rho-based solvers, inheriting the functionality from the basic model. They then use those as template parameter for inheritance for all the different models. So that each solver has a specific mechLaw useful for it but there is still only one code base to maintain.

Thinking about the mechanicalLaws, we could create a basicMechanicalLaw with the basic functionality like solid-submeshes and then different sub-bases for small strain (maybe even divided into incremental and total), total-lagrangian and updated lagrangian. then these can be template-inherited from in the actual machanical laws. 

On top of keeping the code clean, this makes it easy to extend the capabilities
(e.g. for an eularianMechanicalLaw ;) )
