### ISSUE TITLE
The K() function in mechanicalLaw.H returns an empty field

### ISSUE THREAD

**Issue by philipcardiff** [solids4foam/solids4foam#90]
The K() function in mechanicalLaw.H returns an empty field, so it is possible that the developer of a new mechanical may inadvertently use this empty field. Currently, K() is used by various hyperelastic laws where the laws set the value when first calling K().

A better solution would be to have two interfaces:
- K(const dimensionedScalar& k): this would create the field and set its value to k. If the field already exists, we could return an error or reset the value.
- K(): this would return the field if it was already created; otherwise it would give an error saying that the field must first be created with K(const dimensionedScalar& k)

**Comment by iBatistic** [comment]
@philipcardiff, we have the same problem with the mu() field, right?

Is the first method you suggest the `void` function?

Both options look good to me; I am willing to make these changes if you wish (when you decide which option).

**Comment by philipcardiff** [comment]
Yep, we have the same problem with `mu()`, `muf()`,` K()` and `Kf()`. I think these were all added when updating the hyperelastic laws (pinging @iagolessa in case you have thoughts).

Currently, if we take `K()` as an example, we have the following four functions:
```
const Foam::volScalarField& Foam::mechanicalLaw::K() const
{
    if (KPtr_.empty())
    {
     	makeK();
    }

    return KPtr_();
}

Foam::volScalarField& Foam::mechanicalLaw::K()
{
    if (KPtr_.empty())
    {
     	makeK();
    }

    return KPtr_();
}

const Foam::volScalarField& Foam::mechanicalLaw::K(const dimensionedScalar& K)
{
    if (KPtr_.empty())
    {
        makeK();
    }

    // Set constant field, overwriting any existing values                                                                                                      
    KPtr_() = K;

    // Return a reference to the field                                                                                                                          
    return KPtr_();
}

void Foam::mechanicalLaw::makeK() const
{
    if (KPtr_.valid())
    {
        FatalErrorIn("void " + type() + "::makeK()")
            << "pointer already set" << abort(FatalError);
    }

    KPtr_.set
    (
        new volScalarField
        (
            // Initialise to 0.0!
        )
    );
}
```

The problem is that K() (const and non-const versions) can be called and return a 0.0 field, where the developer might not realise they need to set this field themselves.

A possible workaround is to edit these two functions as follows (e.g. for the const version):
```
const Foam::volScalarField& Foam::mechanicalLaw::K() const
{
    if (KPtr_.empty())
    {
     	FatalError
            << "K field has not been set. Please construct the field first using K(const dimensionedScalar& K)"
            << abort(FatalError);
    }

    return KPtr_();
}
```
but we would need to check if any changes are required in the hyperelastic laws, which use these functions.
If the developer prefers, they can set the K field anyway they like (using the non-const K() function), however, they must first initialise it to some constant dimensionedScalar.

What do you think? Yes, of course, feel free to make these changes!

**Comment by iBatistic** [comment]
Your solution seems perfectly fine to me. I can't think of anything better.   

> If the developer prefers, they can set the K field anyway they like (using the non-const K() function), however, they must first initialise it to some constant dimensionedScalar.

We currently have models that store and use a dimensionedScalar K_ and one might think that K() will return K_ which is not true because we do not initialize the K field for those models.

> but we would need to check if any changes are required in the hyperelastic laws, which use these functions.

At first glance, it doesn't seem to me that we need changes. Anyway, I'll try to implement this and check it out.

**Comment by iBatistic** [comment]
> but we would need to check if any changes are required in the hyperelastic laws, which use these functions.

you were right, `MooneyRivlinElastic.C` on line `93` is initialising `mu` field using `volScalarField`:

`mu() = 2.0*(c10_ + c01_);`

also K is initialised using `volScalarField E`:

`K() = E/(3.0*(1.0 - 2.0*nu));`

The simplest solution is to initialize it to zero using `dimensionedScalar` a line before this. Another option is to add a new function to `mechanichalLaw` class which will initialize `mu` and `K` using field values.

@philipcardiff  what do you think we should do here?

**Comment by philipcardiff** [comment]
Initialising using a `dimensionedScalar` before its use is simple, albeit from a mechanical law developer perspective, it might seem a bit ugly.

Another solution, as you suggested, is to add a constructor for mu and K that takes a reference to a volScalarField. We could add two constructors, e.g.
```
void makeMu(const volScalarField& mu)
{
    // ...
}
void makeMu(const dimensionedScalar& mu)
{
    // ...
}
```
And then, inside `mu(),` we could give an error if the mu field has not already been created.

I guess this should work, although it is a bit annoying that we would need to add many similar functions to mechanicalLaw.C. It is probably OK for now and better than the current situation.
Maybe there is some generic interface we can create, e.g. store a PtrList of volScalarFields, but this is probably overkill.

**Comment by iBatistic** [comment]
@philipcardiff  I made a PR with additional constructors. Until we get a finer solution, I agree that this is a better solution than nothing.

**Comment by philipcardiff** [comment]
Resolved in https://github.com/solids4foam/solids4foam/pull/102
