### ISSUE TITLE
Convergence issues with s4f 2.0 and OpenFOAM-v2012

### ISSUE THREAD

**Issue by francescoornano** [solids4foam/solids4foam#91]
[membrane_neoHook_press.zip](https://github.com/solids4foam/solids4foam/files/13217769/membrane_neoHook_press.zip)
Hello,
First, thanks for making this great tool available. 

I'm writing because I have been having issues with running a case with solids4Foam v2.0 and OpenFOAM-v2012. The case used to run smooth with solids4Foam v1.0 and foam-extend 4.1.  
It is a simple membrane with imposed time-varying pressure (or displacement) applied to a patch on one side of the membrane. The material is hyperelastic and the constitutive law is neoHookean. I'm attaching the case files. 
I have tried several actions to fix the convergence issue, e.g. added under-relaxations (both fields and equations), changed material properties/constituive law, etc., with no success. 

Any help/support would be greatly appriciated!

Many thanks
Francesco

**Comment by iBatistic** [comment]
Hi Francesco,
did you try solids4foam-v2.0 with fe41?

**Comment by francescoornano** [comment]
Hi Ivan, 
Thanks for the reply. 
I've tried to compile fe41 on my current system based on Ubuntu 22.04 but encountered lots of backward compatibility issues related to compiler versions etc.  
Is this a known issue (for hyperelastic cases)? Would a foundation version of OF work? 
Thanks very much
Francesco

**Comment by francescoornano** [comment]
Hi, 
Just for the sake fo completeness, I solved the issue by installing solids4Foam-v2.0 together with foam-extend-4.1 using Docker [().](https://www.solids4foam.com/installation/installWithDocker.html) 
With fe41, the case run and converged. 
There was definitely a compatibility issue when using OpenFOAM-v2012 instead of foam-extend 4.1.
I'm interested in knowing what caused the issue.  

Francesco

**Comment by iBatistic** [comment]
Hi Francesco, 
I'm glad you solved the problem. 

It should work with other versions as well. I tried openfoam_com and it crashed immediately,  this needs further investigation.

**Comment by philipcardiff** [comment]
I suspect that the fix at https://github.com/solids4foam/solids4foam/issues/105 would also fix the issues you had with Ubuntu 22.04.
